---
name: 'Contributors Action'
author: 'github'
description: 'A GitHub Action to report out contributors and contributions to a repository or organization'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/gsoc2/contributors:main'
branding:
  icon: 'users'
  color: 'green'
